api_version: v1
name: stable-diffusion-demo
operator:
  name: aws-ec2
template: terraform
spec:
  region: us-west-1
  instance_type: g4dn.2xlarge
  # points to Deep Learning AMI GPU PyTorch 1.12.0 (Ubuntu 20.04) 20220913 AMI
  ami_id: ami-0a85a3a3fb34b3c7f
  enable_gpus: true
